---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops
  name: app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: devops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:stable
        imagePullPolicy: Always
        name: nginx-reverse-proxy
        ports:
        - containerPort: 3011
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 70
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items: 
               - key: nginx.conf
                 path: nginx.conf