---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  nginx.conf: |
      events {
        worker_connections 1024;
      }
      
      http {
        log_format  main  "$remote_addr - $remote_user [$time_local] '$request' "
                          "$status $body_bytes_sent '$http_referer' "
                          "'$http_user_agent' 'real-ip: $http_x_forwarded_for' 'response_time: $upstream_response_time'";
      
        access_log  /var/log/nginx/access.log  main;
      
        server {
          listen 3011;
          server_tokens off;

        }
      }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items: 
               - key: nginx.conf
                 path: nginx.conf
      containers:
        - name: cat-file
          image: "public.ecr.aws/ubuntu/ubuntu:latest"
          volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-config
          env:
            - name: SLEEP_TIME
              value: {{ .Values.SLEEP_TIME | quote }}
          command:
            - bash
            - "-c"
            - |
                sleep 5
                echo 1.....
                cat /etc/nginx/nginx.conf
                c=$(($SLEEP_TIME))
                for i in {1..$c}; do echo $i; sleep 1; done